services:
  - type: web
    name: url-shortener
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: DATABASE_URL
        fromDatabase:
          name: url_shortener_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: url-shortener-redis
          property: connectionString

  - type: pserv
    name: url_shortener_db
    env: docker
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10
    envVars:
      - key: POSTGRES_DB
        value: url_shortener
      - key: POSTGRES_USER
        value: url_shortener
      - key: POSTGRES_PASSWORD
        generateValue: true

  - type: redis
    name: url-shortener-redis
    ipAllowList: []
    plan: free 